[Flutter] 10 - Internacionalização
And-PM/acelerate-everest-crypto-listing-challenge pull request #17
Opened 2022-10-10 14:00 UTC by And-PM

### Finalização do Card 10
- [x] internacionalização completa com suporte a inglês e português
- [x] Correção do provider de cripto moeda que agora só passa o modelo e não atributos separados
- [x] Adicionando centralização nos textos default

![Android-Emulator-Pixel_2_API_30_5554-2022-10-07-14-31-39_Trim](https://user-images.githubusercontent.com/113135447/194878676-8891a41f-3d72-4986-b7bf-0ae3650398d4.gif)

2022-10-10 19:17 UTC, guilhermeqmaia approved these changes
Embora não esteja relacionado a esse card, o TextFormField da tela de conversão precisa de validador

Eu abri o emulador e consegui colocar um valor muito acima do saldo que aparecia que eu tinha da moeda e além de isso estar logicamente errado, acabou causando um overflow na tela de transações porque o número era gigantesco.

Acrescentando, os returns do validator devem ser internacionalizados

2022-10-11 12:02 UTC, julialuciani approved these changes

2022-10-14 12:31 UTC, CarlosTSIlva requested changes
assim q ajustar me chamar

2022-10-14 12:31 UTC, CarlosTSIlva commented on lib/convert/view/convert_screen.dart
>    const ConvertScreen({Key? key}) : super(key: key);
porque a troca?

2022-10-14 12:31 UTC, carlosTsilva commented on lib/review/widgets/review_body.dart
> +                  : 0.0,
daria pra ser ref.watch(fieldTransferValue.state).state  ?? 0.0 nao?

2022-10-14 12:31 UTC, carlosTsilva commented on lib/shared/providers/providers.dart
> +        marketCapChangePercentage24h: 0.0));
porque da o init valué aqui se a classe tu tem essa permissão  n coloca requier e coloca valores iniciais

2022-10-14 13:02 UTC, And-PM commented on lib/review/widgets/review_body.dart
> +                  : 0.0,
Alterado

2022-10-14 13:04 UTC, AndreMartinsWarren commented on lib/convert/view/convert_screen.dart
>    const ConvertScreen({Key? key}) : super(key: key);
Creio que tenha voltado para a versão anterior do arquivo, por isso ele havia voltado a ser HookConsumerWidget, já alterei novamente para Stateless

2022-10-14 13:04 UTC, And-PM commented on lib/shared/providers/providers.dart
> +        marketCapChangePercentage24h: 0.0));
alterado

2022-10-14 13:29 UTC, merged