Feat/ev-772/componetization
And-PM/acelerate-everest-crypto-listing-challenge pull request #3
Opened 2022-09-12 20:25 UTC by And-PM

### Finalizado Card 3 - Componentização
Visualmente não houveram alterações, porém todos os widgets foram componentizados.
Os widgets extraídos foram o seguinte:
![image](https://user-images.githubusercontent.com/113135447/189902533-cb785629-0ce4-423a-bb29-2ec8393a8cfb.png)

2022-09-13 15:04 UTC, CamileBarros reviewed
vamos tentar seguir ao maximo o padrão de arquitetura presente nessa [doc](https://www.notion.so/warrenbrasil/Uma-id-ia-para-Arquitetura-dos-Microfrontends-23b055ca716b46aa969e7f6a36fd17f7), use os exemplos em imagem que estão no card.

2022-09-13 16:26 UTC, CamileBarros requested changes

2022-09-13 16:26 UTC, CamileBarros commented on lib/wallet_presenter/wallet_screen.dart
> +final hideWalletStateProvider = StateProvider((ref) => true);
pode ficar isolado em uma package destinada a providers dessa tela

2022-09-13 16:26 UTC, CamileBarros commented on lib/wallet_presenter/wallet_screen.dart
>    const WalletScreen({Key? key}) : super(key: key);
Essa tela pode ser Stateless

2022-09-13 16:26 UTC, CamileBarros commented on lib/wallet_presenter/wallet_screen.dart
> +              child: ListView(
Verifica essa [doc](https://api.flutter.dev/flutter/widgets/ListView-class.html), porque você aqui acaba precisando inserir cada novo item na lista, fica redundante, na doc tem uma forma de otimizar isso.

2022-09-13 16:26 UTC, CamileBarros commented on lib/wallet_presenter/wallet_screen.dart
> +                    abbreviation: 'BTC',
Por que não passa teus dados para uma data source mockada?

2022-09-13 16:26 UTC, CamileBarros commented on lib/wallet_presenter/widgets/navbar_wallet.dart
> +        BottomNavigationBarItem(
Tua bottomNavigationBar é um widget compartilhado com todo seu projeto, não somente com a wallet, você pode ajustar melhor ela na estruturação

2022-09-13 18:57 UTC, And-PM commented on lib/wallet_presenter/wallet_screen.dart
>    const WalletScreen({Key? key}) : super(key: key);
Essa tela usa mudança de estado para ocultar os valores monetários, então não consigo tirar o Stateful

2022-09-13 19:19 UTC, And-PM commented on lib/wallet_presenter/wallet_screen.dart
> +final hideWalletStateProvider = StateProvider((ref) => true);
Feito

2022-09-13 19:19 UTC, And-PM commented on lib/wallet_presenter/wallet_screen.dart
> +              child: ListView(
feito, solucionado com riverpod

2022-09-13 19:20 UTC, And-PM commented on lib/wallet_presenter/wallet_screen.dart
> +                    abbreviation: 'BTC',
feito

2022-09-13 19:20 UTC, AndreMartinsWarren commented on lib/wallet_presenter/widgets/navbar_wallet.dart
> +        BottomNavigationBarItem(
feito

2022-09-14 21:18 UTC, And-PM commented
### Correções efetuadas com base na branch Study:
abaixo a nova arquitetura de pastas:
![image](https://user-images.githubusercontent.com/113135447/190264294-6e1e7531-ecba-48f5-b3bd-4a42772ce4a5.png)

2022-09-15 11:34 UTC, CamileBarros approved these changes

2022-09-15 11:39 UTC, merged